services:
- docker:dind

stages:
- build
- release

build:
  stage: build
  image: registry.gitlab.com/flownative/docker/beach-phpfpm-did:7.2
  variables:
    GIT_SSH_COMMAND: 'ssh -o PreferredAuthentications=publickey -i ~/.ssh/deploymentkey_rsa'
  script:
  - build/build.sh
  artifacts:
    paths:
    - beach.phar
    expire_in: '1 hour'
  only:
  - tags

release:
  stage: release
  image: registry.gitlab.com/flownative/docker/beach-phpfpm-did:7.2
  variables:
    GIT_SSH_COMMAND: 'ssh -o PreferredAuthentications=publickey -i ~/.ssh/deploymentkey_rsa -i ~/.ssh/github_deploymentkey_rsa'
  script:
  - build/release.sh
  only:
  - tags
