version: '3.5'

networks:
  local_beach:
    name: local_beach

services:
  nginx:
    image: flownative/localbeach-nginx-proxy:0.1.1
    container_name: local_beach_nginx
    networks:
      - local_beach
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=hello.localbeach.net
  database:
    image: mariadb:10.2
    container_name: local_beach_database
    networks:
      - local_beach
    volumes:
      - {{databaseFolder}}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
       - 3307:3306
    command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'
