services:
    _defaults:
      public: true
      autowire: false
      autoconfigure: false

    configuration:
      class:     'Flownative\Beach\Cli\Service\ConfigurationService'

    resources_download:
      class: 'Flownative\Beach\Cli\Command\Resources\DownloadCommand'
      calls:
        - [setConfig, ['@configuration']]

    projects_init:
      class: 'Flownative\Beach\Cli\Command\Projects\InitCommand'
