services:
    _defaults:
      public: true
      autowire: false
      autoconfigure: false

    configuration:
      class:     'Flownative\Beach\Cli\Service\ConfigurationService'

    resources_download:
      class: 'Flownative\Beach\Cli\Command\Resources\DownloadCommand'
      calls:
        - [setConfig, ['@configuration']]

    local_init:
      class: 'Flownative\Beach\Cli\Command\Local\InitCommand'

    localbeach_prepare:
      class: 'Flownative\Beach\Cli\Command\LocalBeach\PrepareCommand'

    localbeach_start:
      class: 'Flownative\Beach\Cli\Command\LocalBeach\StartCommand'

    localbeach_stop:
      class: 'Flownative\Beach\Cli\Command\LocalBeach\StopCommand'

    localbeach_setup:
      class: 'Flownative\Beach\Cli\Command\LocalBeach\SetupCommand'
