services:
    _defaults:
      public: true
      autowire: false
      autoconfigure: false

    hello:
      class: 'Flownative\Beach\Cli\Command\HelloCommand'
      calls:
        - [setConfig, ['@configuration']]

    configuration:
      class:     'Flownative\Beach\Cli\Service\ConfigurationService'

    resources_download:
      class: 'Flownative\Beach\Cli\Command\Resources\DownloadCommand'
      calls:
        - [setConfig, ['@configuration']]
